[package]
name = "doppler-swarm"
version = "0.1.0"
edition = "2021"
authors = ["Pavel Lazureykis <pavel@lazureykis.dev>"]
description = "Watch for changes in Doppler and update your Docker Swarm services."
license = "MIT"
homepage = "https://github.com/whopio/doppler-swarm/"
categories = ["command-line-utilities"]
keywords = ["doppler", "docker swarm", "secrets", "configuration"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bollard = { version = "0.15.0", features = ["tokio-stream"] }
bytes = "1.5.0"
futures = "0.3.30"
reqwest = { version = "0.11.23", features = ["stream", "json"] }
serde = { version = "1.0.194", features = ["derive"] }
serde_json = "1.0.110"
tokio = { version = "1.35.1", features = ["full"] }
